name: Cron HealthTrack - Emails

on:
  schedule:
    - cron: "0 12 * * 1"  # Segunda às 09h BRT → 12h UTC
  workflow_dispatch:

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "22"
      - run: npm install
      - run: node cron.js emails
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_NAME: ${{ secrets.SENDER_NAME }}
