name: Cron HealthTrack - Pacientes

on:
  schedule:
    - cron: "0 3 * * *" # Todo dia à meia-noite BRT
  workflow_dispatch:

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Run cron
        run: node cron.js pacientes
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
